export const SOCKET_IO_CONNECTING = 'SOCKET_IO_CONNECTING';
export const SOCKET_IO_CONNECT = 'SOCKET_IO_CONNECT';
export const SOCKET_IO_DISCONNECT = 'SOCKET_IO_DISCONNECT';
export const SOCKET_IO_CONNECTED = 'SOCKET_IO_CONNECTED';
export const SOCKET_IO_DISCONNECTED = 'SOCKET_IO_DISCONNECTED';
export const SOCKET_IO_EMIT = 'SOCKET_IO_EMIT';
export const DB_UPDATE = 'DB_UPDATE';